### ISSUE TITLE
How do I find your paper published in SIGIR2022

### ISSUE THREAD

**Issue by leexk312** [CRIPAC-DIG/CF-FEND#1]
Hello I'd like to read your paper“Counterfacutal Debiasing for Evidence-aware Fake News Detection”，but  I cant find it in any search engine.

**Comment by Hyperwjf** [comment]
Hi!
Could you leave an email? We will send the paper to you.

**Comment by leexk312** [comment]
ok its 1209427546@stu.cqut.edu.cn thank you so much!

**Comment by DepartingWind** [comment]
> 

Could you please send me this paper? My email address is: hcy_866@163.com
Thank you very much!

**Comment by Hyperwjf** [comment]
@xiaoyaoqingchun 
Hi! This paper has been published in SIGIR2022. You can get it at https://dl.acm.org/doi/10.1145/3477495.3531850.
